version: "3"

services:

  # Routing engine
  bird: 
    build:
      context: ./services/bird
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./services/bird/etc/bird.conf:/usr/local/etc/bird.conf
      - ./services/bird/var/run:/usr/local/var/run
    cap_add:
      - NET_ADMIN

  # NAT64
  tayga:
    build:
      context: ./services/tayga
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      SNAT_IPV4: 23.142.232.26
      TAYGA_IPV6: "2602:faf5:64::64"
      WAN_INTERFACE: enp1s0
    privileged: true

  # DNS64
  coredns:
    depends_on:
      - tayga
    image: coredns/coredns:latest
    restart: unless-stopped
    #network_mode: host
    # ports:
    #   - "[::]:53:53/udp"
    volumes:
      - ./services/coredns/Corefile:/etc/coredns/Corefile
    command: 
      - -conf
      - /etc/coredns/Corefile
    networks:
      - internal
        # ipv6_address: "2602:faf5:64::"

  # Bird exporter
  bird_exporter:
    image: czerwonk/bird_exporter:latest
    depends_on:
      - bird
    restart: unless-stopped
    volumes:
      - ./services/bird/var/run:/external/var/run
    command:
      - -bird.v2
      - -format.new=true
      - -bird.socket=/external/var/run/bird.ctl
    networks:
      - internal

  # Node exporter
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    # network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - internal

  # Exporter exporter
  exporter_exporter:
    depends_on:
      - coredns
      - bird_exporter
      - node_exporter
    image: qubitproducts/exporter_exporter:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./services/expexp/expexp.yaml:/etc/expexp/expexp.yaml
    command:
      - -config.file=/etc/expexp/expexp.yaml
    networks:
      internal: 
        ipv6_address: "2602:faf5:64::9999"
    
networks:
  internal:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2602:faf5:64::/64
          gateway: 2602:faf5:64::1